name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Build
        run: |
          CAUSE="Triggered+by+GitHook"
          curl "https://${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_PASSWORD }}@${{ secrets.JENKINS_DOMAIN }}/job/workshop2/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}" \
            -d "LOCAL_TARGET=true" \
            -d "REMOTE_TARGET=true" \
            -d "FIREBASE_TARGET=true" \
            -d "cause=$CAUSE" \
            -H 'ngrok-skip-browser-warning: yes'
